//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGDeliveryWPF.SalesServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesTable", Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    [System.SerializableAttribute()]
    public partial class SalesTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeliveryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HalfPalletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FGDeliveryWPF.SalesServices.SalesLine[] LinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PickSameDimensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartLoadingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StopLoadingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TruckPlateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeliveryDate {
            get {
                return this.DeliveryDateField;
            }
            set {
                if ((this.DeliveryDateField.Equals(value) != true)) {
                    this.DeliveryDateField = value;
                    this.RaisePropertyChanged("DeliveryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryMode {
            get {
                return this.DeliveryModeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryModeField, value) != true)) {
                    this.DeliveryModeField = value;
                    this.RaisePropertyChanged("DeliveryMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryName {
            get {
                return this.DeliveryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryNameField, value) != true)) {
                    this.DeliveryNameField = value;
                    this.RaisePropertyChanged("DeliveryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverName {
            get {
                return this.DriverNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverNameField, value) != true)) {
                    this.DriverNameField = value;
                    this.RaisePropertyChanged("DriverName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HalfPallet {
            get {
                return this.HalfPalletField;
            }
            set {
                if ((this.HalfPalletField.Equals(value) != true)) {
                    this.HalfPalletField = value;
                    this.RaisePropertyChanged("HalfPallet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FGDeliveryWPF.SalesServices.SalesLine[] Lines {
            get {
                return this.LinesField;
            }
            set {
                if ((object.ReferenceEquals(this.LinesField, value) != true)) {
                    this.LinesField = value;
                    this.RaisePropertyChanged("Lines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PickSameDimension {
            get {
                return this.PickSameDimensionField;
            }
            set {
                if ((this.PickSameDimensionField.Equals(value) != true)) {
                    this.PickSameDimensionField = value;
                    this.RaisePropertyChanged("PickSameDimension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickingId {
            get {
                return this.PickingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PickingIdField, value) != true)) {
                    this.PickingIdField = value;
                    this.RaisePropertyChanged("PickingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesId {
            get {
                return this.SalesIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesIdField, value) != true)) {
                    this.SalesIdField = value;
                    this.RaisePropertyChanged("SalesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesName {
            get {
                return this.SalesNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesNameField, value) != true)) {
                    this.SalesNameField = value;
                    this.RaisePropertyChanged("SalesName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartLoading {
            get {
                return this.StartLoadingField;
            }
            set {
                if ((this.StartLoadingField.Equals(value) != true)) {
                    this.StartLoadingField = value;
                    this.RaisePropertyChanged("StartLoading");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StopLoading {
            get {
                return this.StopLoadingField;
            }
            set {
                if ((this.StopLoadingField.Equals(value) != true)) {
                    this.StopLoadingField = value;
                    this.RaisePropertyChanged("StopLoading");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TruckPlate {
            get {
                return this.TruckPlateField;
            }
            set {
                if ((object.ReferenceEquals(this.TruckPlateField, value) != true)) {
                    this.TruckPlateField = value;
                    this.RaisePropertyChanged("TruckPlate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesLine", Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    [System.SerializableAttribute()]
    public partial class SalesLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExclusiveHalfPalletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHalfPalletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LineRecIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FGDeliveryWPF.SalesServices.InventByGrLocContract[] LocationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SalesQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SalesQtyBoxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SalesQtyPalletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SalesQtySQMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SalesQtySQMRemainingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SalesQtySQMReservedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarehouseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExclusiveHalfPallet {
            get {
                return this.ExclusiveHalfPalletField;
            }
            set {
                if ((this.ExclusiveHalfPalletField.Equals(value) != true)) {
                    this.ExclusiveHalfPalletField = value;
                    this.RaisePropertyChanged("ExclusiveHalfPallet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeField, value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHalfPallet {
            get {
                return this.IsHalfPalletField;
            }
            set {
                if ((this.IsHalfPalletField.Equals(value) != true)) {
                    this.IsHalfPalletField = value;
                    this.RaisePropertyChanged("IsHalfPallet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LineRecId {
            get {
                return this.LineRecIdField;
            }
            set {
                if ((this.LineRecIdField.Equals(value) != true)) {
                    this.LineRecIdField = value;
                    this.RaisePropertyChanged("LineRecId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FGDeliveryWPF.SalesServices.InventByGrLocContract[] Locations {
            get {
                return this.LocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationsField, value) != true)) {
                    this.LocationsField = value;
                    this.RaisePropertyChanged("Locations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickingId {
            get {
                return this.PickingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PickingIdField, value) != true)) {
                    this.PickingIdField = value;
                    this.RaisePropertyChanged("PickingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesId {
            get {
                return this.SalesIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesIdField, value) != true)) {
                    this.SalesIdField = value;
                    this.RaisePropertyChanged("SalesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SalesQty {
            get {
                return this.SalesQtyField;
            }
            set {
                if ((this.SalesQtyField.Equals(value) != true)) {
                    this.SalesQtyField = value;
                    this.RaisePropertyChanged("SalesQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SalesQtyBox {
            get {
                return this.SalesQtyBoxField;
            }
            set {
                if ((this.SalesQtyBoxField.Equals(value) != true)) {
                    this.SalesQtyBoxField = value;
                    this.RaisePropertyChanged("SalesQtyBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SalesQtyPallet {
            get {
                return this.SalesQtyPalletField;
            }
            set {
                if ((this.SalesQtyPalletField.Equals(value) != true)) {
                    this.SalesQtyPalletField = value;
                    this.RaisePropertyChanged("SalesQtyPallet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SalesQtySQM {
            get {
                return this.SalesQtySQMField;
            }
            set {
                if ((this.SalesQtySQMField.Equals(value) != true)) {
                    this.SalesQtySQMField = value;
                    this.RaisePropertyChanged("SalesQtySQM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SalesQtySQMRemaining {
            get {
                return this.SalesQtySQMRemainingField;
            }
            set {
                if ((this.SalesQtySQMRemainingField.Equals(value) != true)) {
                    this.SalesQtySQMRemainingField = value;
                    this.RaisePropertyChanged("SalesQtySQMRemaining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SalesQtySQMReserved {
            get {
                return this.SalesQtySQMReservedField;
            }
            set {
                if ((this.SalesQtySQMReservedField.Equals(value) != true)) {
                    this.SalesQtySQMReservedField = value;
                    this.RaisePropertyChanged("SalesQtySQMReserved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesUnit {
            get {
                return this.SalesUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesUnitField, value) != true)) {
                    this.SalesUnitField = value;
                    this.RaisePropertyChanged("SalesUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Site {
            get {
                return this.SiteField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteField, value) != true)) {
                    this.SiteField = value;
                    this.RaisePropertyChanged("Site");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Size {
            get {
                return this.SizeField;
            }
            set {
                if ((object.ReferenceEquals(this.SizeField, value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateType {
            get {
                return this.UpdateTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateTypeField, value) != true)) {
                    this.UpdateTypeField = value;
                    this.RaisePropertyChanged("UpdateType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdatedByField, value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warehouse {
            get {
                return this.WarehouseField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseField, value) != true)) {
                    this.WarehouseField = value;
                    this.RaisePropertyChanged("Warehouse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventByGrLocContract", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    [System.SerializableAttribute()]
    public partial class InventByGrLocContract : FGDeliveryWPF.SalesServices.XppObjectBase {
        
        private string gradeFieldField;
        
        private string locationIdFieldField;
        
        private decimal onHandFieldField;
        
        private bool onHandFieldSpecifiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string gradeField {
            get {
                return this.gradeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.gradeFieldField, value) != true)) {
                    this.gradeFieldField = value;
                    this.RaisePropertyChanged("gradeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string locationIdField {
            get {
                return this.locationIdFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.locationIdFieldField, value) != true)) {
                    this.locationIdFieldField = value;
                    this.RaisePropertyChanged("locationIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal onHandField {
            get {
                return this.onHandFieldField;
            }
            set {
                if ((this.onHandFieldField.Equals(value) != true)) {
                    this.onHandFieldField = value;
                    this.RaisePropertyChanged("onHandField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool onHandFieldSpecified {
            get {
                return this.onHandFieldSpecifiedField;
            }
            set {
                if ((this.onHandFieldSpecifiedField.Equals(value) != true)) {
                    this.onHandFieldSpecifiedField = value;
                    this.RaisePropertyChanged("onHandFieldSpecified");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FGDeliveryWPF.SalesServices.PalletItemContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FGDeliveryWPF.SalesServices.CustomerDeliveryContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FGDeliveryWPF.SalesServices.FGLineContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FGDeliveryWPF.SalesServices.FGDeliveryContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FGDeliveryWPF.SalesServices.InventByGrLocContract))]
    public partial class XppObjectBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.ComponentModel.PropertyChangedEventHandler PropertyChanged1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="PropertyChanged", IsRequired=true)]
        public System.ComponentModel.PropertyChangedEventHandler PropertyChanged1 {
            get {
                return this.PropertyChanged1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyChanged1Field, value) != true)) {
                    this.PropertyChanged1Field = value;
                    this.RaisePropertyChanged("PropertyChanged1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PalletItemContract", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    [System.SerializableAttribute()]
    public partial class PalletItemContract : FGDeliveryWPF.SalesServices.XppObjectBase {
        
        private string serialFieldField;
        
        private string updatedByFieldField;
        
        private System.DateTime updatedDateFieldField;
        
        private bool updatedDateFieldSpecifiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string serialField {
            get {
                return this.serialFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.serialFieldField, value) != true)) {
                    this.serialFieldField = value;
                    this.RaisePropertyChanged("serialField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string updatedByField {
            get {
                return this.updatedByFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.updatedByFieldField, value) != true)) {
                    this.updatedByFieldField = value;
                    this.RaisePropertyChanged("updatedByField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime updatedDateField {
            get {
                return this.updatedDateFieldField;
            }
            set {
                if ((this.updatedDateFieldField.Equals(value) != true)) {
                    this.updatedDateFieldField = value;
                    this.RaisePropertyChanged("updatedDateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool updatedDateFieldSpecified {
            get {
                return this.updatedDateFieldSpecifiedField;
            }
            set {
                if ((this.updatedDateFieldSpecifiedField.Equals(value) != true)) {
                    this.updatedDateFieldSpecifiedField = value;
                    this.RaisePropertyChanged("updatedDateFieldSpecified");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDeliveryContract", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    [System.SerializableAttribute()]
    public partial class CustomerDeliveryContract : FGDeliveryWPF.SalesServices.XppObjectBase {
        
        private string customerAccountFieldField;
        
        private string customerNameFieldField;
        
        private string packingSlipNumFieldField;
        
        private decimal quantityFieldField;
        
        private bool quantityFieldSpecifiedField;
        
        private int trucksFieldField;
        
        private bool trucksFieldSpecifiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string customerAccountField {
            get {
                return this.customerAccountFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.customerAccountFieldField, value) != true)) {
                    this.customerAccountFieldField = value;
                    this.RaisePropertyChanged("customerAccountField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string customerNameField {
            get {
                return this.customerNameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.customerNameFieldField, value) != true)) {
                    this.customerNameFieldField = value;
                    this.RaisePropertyChanged("customerNameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string packingSlipNumField {
            get {
                return this.packingSlipNumFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.packingSlipNumFieldField, value) != true)) {
                    this.packingSlipNumFieldField = value;
                    this.RaisePropertyChanged("packingSlipNumField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal quantityField {
            get {
                return this.quantityFieldField;
            }
            set {
                if ((this.quantityFieldField.Equals(value) != true)) {
                    this.quantityFieldField = value;
                    this.RaisePropertyChanged("quantityField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool quantityFieldSpecified {
            get {
                return this.quantityFieldSpecifiedField;
            }
            set {
                if ((this.quantityFieldSpecifiedField.Equals(value) != true)) {
                    this.quantityFieldSpecifiedField = value;
                    this.RaisePropertyChanged("quantityFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int trucksField {
            get {
                return this.trucksFieldField;
            }
            set {
                if ((this.trucksFieldField.Equals(value) != true)) {
                    this.trucksFieldField = value;
                    this.RaisePropertyChanged("trucksField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool trucksFieldSpecified {
            get {
                return this.trucksFieldSpecifiedField;
            }
            set {
                if ((this.trucksFieldSpecifiedField.Equals(value) != true)) {
                    this.trucksFieldSpecifiedField = value;
                    this.RaisePropertyChanged("trucksFieldSpecified");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FGLineContract", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    [System.SerializableAttribute()]
    public partial class FGLineContract : FGDeliveryWPF.SalesServices.XppObjectBase {
        
        private string fGLineNameFieldField;
        
        private int fGLineNumberFieldField;
        
        private bool fGLineNumberFieldSpecifiedField;
        
        private int onGateNumFieldField;
        
        private bool onGateNumFieldSpecifiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fGLineNameField {
            get {
                return this.fGLineNameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.fGLineNameFieldField, value) != true)) {
                    this.fGLineNameFieldField = value;
                    this.RaisePropertyChanged("fGLineNameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int fGLineNumberField {
            get {
                return this.fGLineNumberFieldField;
            }
            set {
                if ((this.fGLineNumberFieldField.Equals(value) != true)) {
                    this.fGLineNumberFieldField = value;
                    this.RaisePropertyChanged("fGLineNumberField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool fGLineNumberFieldSpecified {
            get {
                return this.fGLineNumberFieldSpecifiedField;
            }
            set {
                if ((this.fGLineNumberFieldSpecifiedField.Equals(value) != true)) {
                    this.fGLineNumberFieldSpecifiedField = value;
                    this.RaisePropertyChanged("fGLineNumberFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int onGateNumField {
            get {
                return this.onGateNumFieldField;
            }
            set {
                if ((this.onGateNumFieldField.Equals(value) != true)) {
                    this.onGateNumFieldField = value;
                    this.RaisePropertyChanged("onGateNumField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool onGateNumFieldSpecified {
            get {
                return this.onGateNumFieldSpecifiedField;
            }
            set {
                if ((this.onGateNumFieldSpecifiedField.Equals(value) != true)) {
                    this.onGateNumFieldSpecifiedField = value;
                    this.RaisePropertyChanged("onGateNumFieldSpecified");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FGDeliveryContract", Namespace="http://schemas.datacontract.org/2004/07/SyncServices.SalesOrderAX")]
    [System.SerializableAttribute()]
    public partial class FGDeliveryContract : FGDeliveryWPF.SalesServices.XppObjectBase {
        
        private System.DateTime deliveryDateFieldField;
        
        private bool deliveryDateFieldSpecifiedField;
        
        private int lineNumFieldField;
        
        private bool lineNumFieldSpecifiedField;
        
        private string pickingIdFieldField;
        
        private string ticketFieldField;
        
        private string truckDriverFieldField;
        
        private string truckPlateNumFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime deliveryDateField {
            get {
                return this.deliveryDateFieldField;
            }
            set {
                if ((this.deliveryDateFieldField.Equals(value) != true)) {
                    this.deliveryDateFieldField = value;
                    this.RaisePropertyChanged("deliveryDateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool deliveryDateFieldSpecified {
            get {
                return this.deliveryDateFieldSpecifiedField;
            }
            set {
                if ((this.deliveryDateFieldSpecifiedField.Equals(value) != true)) {
                    this.deliveryDateFieldSpecifiedField = value;
                    this.RaisePropertyChanged("deliveryDateFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int lineNumField {
            get {
                return this.lineNumFieldField;
            }
            set {
                if ((this.lineNumFieldField.Equals(value) != true)) {
                    this.lineNumFieldField = value;
                    this.RaisePropertyChanged("lineNumField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool lineNumFieldSpecified {
            get {
                return this.lineNumFieldSpecifiedField;
            }
            set {
                if ((this.lineNumFieldSpecifiedField.Equals(value) != true)) {
                    this.lineNumFieldSpecifiedField = value;
                    this.RaisePropertyChanged("lineNumFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string pickingIdField {
            get {
                return this.pickingIdFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pickingIdFieldField, value) != true)) {
                    this.pickingIdFieldField = value;
                    this.RaisePropertyChanged("pickingIdField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ticketField {
            get {
                return this.ticketFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ticketFieldField, value) != true)) {
                    this.ticketFieldField = value;
                    this.RaisePropertyChanged("ticketField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string truckDriverField {
            get {
                return this.truckDriverFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.truckDriverFieldField, value) != true)) {
                    this.truckDriverFieldField = value;
                    this.RaisePropertyChanged("truckDriverField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string truckPlateNumField {
            get {
                return this.truckPlateNumFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.truckPlateNumFieldField, value) != true)) {
                    this.truckPlateNumFieldField = value;
                    this.RaisePropertyChanged("truckPlateNumField");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesServices.ISalesService")]
    public interface ISalesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/FindSalesOrder", ReplyAction="http://tempuri.org/ISalesService/FindSalesOrderResponse")]
        FGDeliveryWPF.SalesServices.SalesTable FindSalesOrder(string salesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/FindSalesOrder", ReplyAction="http://tempuri.org/ISalesService/FindSalesOrderResponse")]
        System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesTable> FindSalesOrderAsync(string salesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/FindPickingList", ReplyAction="http://tempuri.org/ISalesService/FindPickingListResponse")]
        FGDeliveryWPF.SalesServices.SalesTable FindPickingList(string pickingId, string userName, string device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/FindPickingList", ReplyAction="http://tempuri.org/ISalesService/FindPickingListResponse")]
        System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesTable> FindPickingListAsync(string pickingId, string userName, string device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/ValidatePallets", ReplyAction="http://tempuri.org/ISalesService/ValidatePalletsResponse")]
        FGDeliveryWPF.SalesServices.SalesLine[] ValidatePallets(string salesId, string itemId, string configId, string pickingId, string[] pallets, string userName, string device, long lineRecId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/ValidatePallets", ReplyAction="http://tempuri.org/ISalesService/ValidatePalletsResponse")]
        System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesLine[]> ValidatePalletsAsync(string salesId, string itemId, string configId, string pickingId, string[] pallets, string userName, string device, long lineRecId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/CheckPalletAvailable", ReplyAction="http://tempuri.org/ISalesService/CheckPalletAvailableResponse")]
        FGDeliveryWPF.SalesServices.SalesLine CheckPalletAvailable(string salesId, string itemId, string configId, string pickingId, string pallet, string userName, string device, System.DateTime dtSave, long lineRecId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/CheckPalletAvailable", ReplyAction="http://tempuri.org/ISalesService/CheckPalletAvailableResponse")]
        System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesLine> CheckPalletAvailableAsync(string salesId, string itemId, string configId, string pickingId, string pallet, string userName, string device, System.DateTime dtSave, long lineRecId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/CheckPalletAvailableMulti", ReplyAction="http://tempuri.org/ISalesService/CheckPalletAvailableMultiResponse")]
        FGDeliveryWPF.SalesServices.SalesLine[] CheckPalletAvailableMulti(string salesId, string itemId, string configId, string pickingId, FGDeliveryWPF.SalesServices.PalletItemContract[] pallets, string userName, string device, long lineRecId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/CheckPalletAvailableMulti", ReplyAction="http://tempuri.org/ISalesService/CheckPalletAvailableMultiResponse")]
        System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesLine[]> CheckPalletAvailableMultiAsync(string salesId, string itemId, string configId, string pickingId, FGDeliveryWPF.SalesServices.PalletItemContract[] pallets, string userName, string device, long lineRecId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/UnreservePallet", ReplyAction="http://tempuri.org/ISalesService/UnreservePalletResponse")]
        string UnreservePallet(string pallet, string pickingId, string userName, string device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/UnreservePallet", ReplyAction="http://tempuri.org/ISalesService/UnreservePalletResponse")]
        System.Threading.Tasks.Task<string> UnreservePalletAsync(string pallet, string pickingId, string userName, string device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetLatestPallets", ReplyAction="http://tempuri.org/ISalesService/GetLatestPalletsResponse")]
        FGDeliveryWPF.SalesServices.SalesLine[] GetLatestPallets(string pickingId, string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetLatestPallets", ReplyAction="http://tempuri.org/ISalesService/GetLatestPalletsResponse")]
        System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesLine[]> GetLatestPalletsAsync(string pickingId, string itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/SavePickingLoad", ReplyAction="http://tempuri.org/ISalesService/SavePickingLoadResponse")]
        void SavePickingLoad(string pickingId, System.DateTime startLoad, System.DateTime stopLoad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/SavePickingLoad", ReplyAction="http://tempuri.org/ISalesService/SavePickingLoadResponse")]
        System.Threading.Tasks.Task SavePickingLoadAsync(string pickingId, System.DateTime startLoad, System.DateTime stopLoad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/CustomersDeliveryByQty", ReplyAction="http://tempuri.org/ISalesService/CustomersDeliveryByQtyResponse")]
        FGDeliveryWPF.SalesServices.CustomerDeliveryContract[] CustomersDeliveryByQty(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/CustomersDeliveryByQty", ReplyAction="http://tempuri.org/ISalesService/CustomersDeliveryByQtyResponse")]
        System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.CustomerDeliveryContract[]> CustomersDeliveryByQtyAsync(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/CustomersDeliveryByTrucks", ReplyAction="http://tempuri.org/ISalesService/CustomersDeliveryByTrucksResponse")]
        FGDeliveryWPF.SalesServices.CustomerDeliveryContract[] CustomersDeliveryByTrucks(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/CustomersDeliveryByTrucks", ReplyAction="http://tempuri.org/ISalesService/CustomersDeliveryByTrucksResponse")]
        System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.CustomerDeliveryContract[]> CustomersDeliveryByTrucksAsync(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetPing", ReplyAction="http://tempuri.org/ISalesService/GetPingResponse")]
        string GetPing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetPing", ReplyAction="http://tempuri.org/ISalesService/GetPingResponse")]
        System.Threading.Tasks.Task<string> GetPingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/ReceivePickingList", ReplyAction="http://tempuri.org/ISalesService/ReceivePickingListResponse")]
        FGDeliveryWPF.SalesServices.SalesTable ReceivePickingList(string userName, string device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/ReceivePickingList", ReplyAction="http://tempuri.org/ISalesService/ReceivePickingListResponse")]
        System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesTable> ReceivePickingListAsync(string userName, string device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/SaveLoginHistory", ReplyAction="http://tempuri.org/ISalesService/SaveLoginHistoryResponse")]
        void SaveLoginHistory(string userName, string device, string deviceIp, string projectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/SaveLoginHistory", ReplyAction="http://tempuri.org/ISalesService/SaveLoginHistoryResponse")]
        System.Threading.Tasks.Task SaveLoginHistoryAsync(string userName, string device, string deviceIp, string projectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetFGLines", ReplyAction="http://tempuri.org/ISalesService/GetFGLinesResponse")]
        FGDeliveryWPF.SalesServices.FGLineContract[] GetFGLines();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetFGLines", ReplyAction="http://tempuri.org/ISalesService/GetFGLinesResponse")]
        System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.FGLineContract[]> GetFGLinesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetDeliveries", ReplyAction="http://tempuri.org/ISalesService/GetDeliveriesResponse")]
        FGDeliveryWPF.SalesServices.FGDeliveryContract[] GetDeliveries(System.DateTime dateSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetDeliveries", ReplyAction="http://tempuri.org/ISalesService/GetDeliveriesResponse")]
        System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.FGDeliveryContract[]> GetDeliveriesAsync(System.DateTime dateSearch);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalesServiceChannel : FGDeliveryWPF.SalesServices.ISalesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesServiceClient : System.ServiceModel.ClientBase<FGDeliveryWPF.SalesServices.ISalesService>, FGDeliveryWPF.SalesServices.ISalesService {
        
        public SalesServiceClient() {
        }
        
        public SalesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FGDeliveryWPF.SalesServices.SalesTable FindSalesOrder(string salesId) {
            return base.Channel.FindSalesOrder(salesId);
        }
        
        public System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesTable> FindSalesOrderAsync(string salesId) {
            return base.Channel.FindSalesOrderAsync(salesId);
        }
        
        public FGDeliveryWPF.SalesServices.SalesTable FindPickingList(string pickingId, string userName, string device) {
            return base.Channel.FindPickingList(pickingId, userName, device);
        }
        
        public System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesTable> FindPickingListAsync(string pickingId, string userName, string device) {
            return base.Channel.FindPickingListAsync(pickingId, userName, device);
        }
        
        public FGDeliveryWPF.SalesServices.SalesLine[] ValidatePallets(string salesId, string itemId, string configId, string pickingId, string[] pallets, string userName, string device, long lineRecId) {
            return base.Channel.ValidatePallets(salesId, itemId, configId, pickingId, pallets, userName, device, lineRecId);
        }
        
        public System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesLine[]> ValidatePalletsAsync(string salesId, string itemId, string configId, string pickingId, string[] pallets, string userName, string device, long lineRecId) {
            return base.Channel.ValidatePalletsAsync(salesId, itemId, configId, pickingId, pallets, userName, device, lineRecId);
        }
        
        public FGDeliveryWPF.SalesServices.SalesLine CheckPalletAvailable(string salesId, string itemId, string configId, string pickingId, string pallet, string userName, string device, System.DateTime dtSave, long lineRecId) {
            return base.Channel.CheckPalletAvailable(salesId, itemId, configId, pickingId, pallet, userName, device, dtSave, lineRecId);
        }
        
        public System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesLine> CheckPalletAvailableAsync(string salesId, string itemId, string configId, string pickingId, string pallet, string userName, string device, System.DateTime dtSave, long lineRecId) {
            return base.Channel.CheckPalletAvailableAsync(salesId, itemId, configId, pickingId, pallet, userName, device, dtSave, lineRecId);
        }
        
        public FGDeliveryWPF.SalesServices.SalesLine[] CheckPalletAvailableMulti(string salesId, string itemId, string configId, string pickingId, FGDeliveryWPF.SalesServices.PalletItemContract[] pallets, string userName, string device, long lineRecId) {
            return base.Channel.CheckPalletAvailableMulti(salesId, itemId, configId, pickingId, pallets, userName, device, lineRecId);
        }
        
        public System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesLine[]> CheckPalletAvailableMultiAsync(string salesId, string itemId, string configId, string pickingId, FGDeliveryWPF.SalesServices.PalletItemContract[] pallets, string userName, string device, long lineRecId) {
            return base.Channel.CheckPalletAvailableMultiAsync(salesId, itemId, configId, pickingId, pallets, userName, device, lineRecId);
        }
        
        public string UnreservePallet(string pallet, string pickingId, string userName, string device) {
            return base.Channel.UnreservePallet(pallet, pickingId, userName, device);
        }
        
        public System.Threading.Tasks.Task<string> UnreservePalletAsync(string pallet, string pickingId, string userName, string device) {
            return base.Channel.UnreservePalletAsync(pallet, pickingId, userName, device);
        }
        
        public FGDeliveryWPF.SalesServices.SalesLine[] GetLatestPallets(string pickingId, string itemId) {
            return base.Channel.GetLatestPallets(pickingId, itemId);
        }
        
        public System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesLine[]> GetLatestPalletsAsync(string pickingId, string itemId) {
            return base.Channel.GetLatestPalletsAsync(pickingId, itemId);
        }
        
        public void SavePickingLoad(string pickingId, System.DateTime startLoad, System.DateTime stopLoad) {
            base.Channel.SavePickingLoad(pickingId, startLoad, stopLoad);
        }
        
        public System.Threading.Tasks.Task SavePickingLoadAsync(string pickingId, System.DateTime startLoad, System.DateTime stopLoad) {
            return base.Channel.SavePickingLoadAsync(pickingId, startLoad, stopLoad);
        }
        
        public FGDeliveryWPF.SalesServices.CustomerDeliveryContract[] CustomersDeliveryByQty(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.CustomersDeliveryByQty(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.CustomerDeliveryContract[]> CustomersDeliveryByQtyAsync(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.CustomersDeliveryByQtyAsync(startDate, endDate);
        }
        
        public FGDeliveryWPF.SalesServices.CustomerDeliveryContract[] CustomersDeliveryByTrucks(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.CustomersDeliveryByTrucks(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.CustomerDeliveryContract[]> CustomersDeliveryByTrucksAsync(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.CustomersDeliveryByTrucksAsync(startDate, endDate);
        }
        
        public string GetPing() {
            return base.Channel.GetPing();
        }
        
        public System.Threading.Tasks.Task<string> GetPingAsync() {
            return base.Channel.GetPingAsync();
        }
        
        public FGDeliveryWPF.SalesServices.SalesTable ReceivePickingList(string userName, string device) {
            return base.Channel.ReceivePickingList(userName, device);
        }
        
        public System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.SalesTable> ReceivePickingListAsync(string userName, string device) {
            return base.Channel.ReceivePickingListAsync(userName, device);
        }
        
        public void SaveLoginHistory(string userName, string device, string deviceIp, string projectName) {
            base.Channel.SaveLoginHistory(userName, device, deviceIp, projectName);
        }
        
        public System.Threading.Tasks.Task SaveLoginHistoryAsync(string userName, string device, string deviceIp, string projectName) {
            return base.Channel.SaveLoginHistoryAsync(userName, device, deviceIp, projectName);
        }
        
        public FGDeliveryWPF.SalesServices.FGLineContract[] GetFGLines() {
            return base.Channel.GetFGLines();
        }
        
        public System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.FGLineContract[]> GetFGLinesAsync() {
            return base.Channel.GetFGLinesAsync();
        }
        
        public FGDeliveryWPF.SalesServices.FGDeliveryContract[] GetDeliveries(System.DateTime dateSearch) {
            return base.Channel.GetDeliveries(dateSearch);
        }
        
        public System.Threading.Tasks.Task<FGDeliveryWPF.SalesServices.FGDeliveryContract[]> GetDeliveriesAsync(System.DateTime dateSearch) {
            return base.Channel.GetDeliveriesAsync(dateSearch);
        }
    }
}
